name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
    uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: WallAshing
      password: ${{ secrets.MY_PAT_TOKEN }}
    run: |
      docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
      docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
      docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest