name: publish php docker image
on: [push]
jobs:
  publish-php-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          command: update
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: wallashing
          password: ${{ secrets.MY_PAT_TOKEN }}
      - name: Test
        run: |
          docker build . --tag ghcr.io/wallashing/publish-php-docker-image:latest
          docker run ghcr.io/wallashing/publish-php-docker-image:latest
          docker push ghcr.io/wallashing/publish-php-docker-image:latest